version: '3'

services:

  database:
    image: mariadb:10.5
    ports:
     - 3306:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_USER: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: wordpress
    networks:
      - frenehard
    volumes:
        - db_data:/var/lib/mysql  
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    networks:
      - frenehard
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
        - db_data:

networks:
    frenehard:
