version: '3'

services:

  database:
    image: mariadb:10.5
    ports:
     - 3306:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_USER: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_PASSWORD: wordpress
    networks:
      - frenehard
    volumes:
      - ${PWD}/volumes/mysql2:/var/lib/mysql
  
  wordpress:
    #image: wordpress:latest
    build: .
    volumes:
      - ${PWD}/volumes/wordpress2/html:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - frenehard
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

networks:
    frenehard:
